CREATE DATABASE IF NOT EXISTS `test` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `test`;

DROP TABLE IF EXISTS `Sample`;

CREATE TABLE IF NOT EXISTS `Sample` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `value` BIGINT(20) DEFAULT NULL,
  `createTime` TIMESTAMP NULL DEFAULT NULL COMMENT 'create time',
  `updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'last modify time',
  PRIMARY KEY (`id`),
  INDEX `name` (`name`),
  INDEX `createTime` (`createTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
