spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: migration/init.sql
    tomcat:
      initial-size: 8
      min-idle: 4
      max-idle: 16
      max-active: 64
      max-wait: 4096
      validation-query: "SELECT 1"
      validation-query-timeout: 60
      test-while-idle: true
      test-on-borrow: false
      time-between-eviction-runs-millis: 18800

mybatis:
  mapper-locations: classpath:demo.dal.dao.mapper/*.xml
  type-aliases-package: demo.common.model.dto
  executor-type: SIMPLE