spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/test?useSSL=false&useUnicode=true&autoReconnect=true&jdbcCompliantTruncation=false
    username: xp
    password: 19531

logging:
  level:
    demo:
      dal:
        dao:
          mapper: TRACE