spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/test?useSSL=false&useUnicode=true&autoReconnect=true&jdbcCompliantTruncation=false
    username: xp
    password: 19531

logging:
  level:
    .: INFO
    org.springframework: 'OFF'
    demo.dal.dao.mapper: TRACE

